In [1]:
import os


In [2]:
os.getcwd()

'C:\\Users\\HP'

In [3]:
os.chdir('E:\Simpli Learn Project Dataset\CSV of different datasets')

In [4]:
os.getcwd()

'E:\\Simpli Learn Project Dataset\\CSV of different datasets'

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
d=pd.read_csv('heart.csv')

In [7]:
d.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [8]:
 #checking null
d.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [9]:
d=d.drop_duplicates()

In [18]:
#Store feature matrix in x and response in y
x=d.drop('target',axis=1)
y=d['target']

In [19]:
x

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     52    1   0       125   212    0        1      168      0      1.0   
1     53    1   0       140   203    1        0      155      1      3.1   
2     70    1   0       145   174    0        1      125      1      2.6   
3     61    1   0       148   203    0        1      161      0      0.0   
4     62    0   0       138   294    1        1      106      0      1.9   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
723   68    0   2       120   211    0        0      115      0      1.5   
733   44    0   2       108   141    0        1      175      0      0.6   
739   52    1   0       128   255    0        1      161      1      0.0   
843   59    1   3       160   273    0        0      125      0      0.0   
878   54    1   0       120   188    0        1      113      0      1.4   

     slope  ca  thal  
0        2   2     3  
1        0   0     3  
2        0   0     3  
3        2   1     3  
4        1   3     2  
..     ...  ..   ...  
723      1   0     2  
733      1   0     2  
739      2   1     3  
843      2   0     2  
878      1   1     3  

[302 rows x 13 columns]

In [20]:
y

0      0
1      0
2      0
3      0
4      0
      ..
723    1
733    1
739    0
843    0
878    0
Name: target, Length: 302, dtype: int64

In [61]:
#train test splittng
from sklearn.model_selection import train_test_split

In [62]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)

In [63]:
from sklearn.ensemble import RandomForestClassifier

In [64]:
rf=RandomForestClassifier()
rf.fit(x_train,y_train)

RandomForestClassifier()

In [65]:
y_pred=rf.predict(x_test)

In [66]:
from sklearn.metrics import accuracy_score

In [75]:
print(accuracy_score(y_test,y_pred))

0.8852459016393442


In [76]:
y_test

363    1
367    0
580    1
216    0
75     1
      ..
380    0
167    1
91     1
166    0
87     0
Name: target, Length: 61, dtype: int64

In [79]:
y_pred

array([1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0], dtype=int64)

In [81]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)

C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [82]:
y_pred

array([1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0], dtype=int64)

In [83]:
y_test

363    1
367    0
580    1
216    0
75     1
      ..
380    0
167    1
91     1
166    0
87     0
Name: target, Length: 61, dtype: int64

In [86]:
print(accuracy_score(y_test,y_pred))

0.8852459016393442


In [87]:
lr=LogisticRegression()
lr.fit(x,y)

C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [88]:
#Saving the model
import joblib

In [89]:
joblib.dump(lr,'Heart disease predictor')

['Heart disease predictor']

In [90]:
#Loading this save model
model=joblib.load('Heart disease predictor')

In [93]:
#creating new dataframe contain data on which prediction to be done
dataNew=pd.DataFrame({'age':23,'sex':1,'cp':1,'trestbps':140,'chol':200,'fbs':1,'restecg':0,'thalach':150,'exang':1,'oldpeak':2.3,'slope':0,'ca':1,'thal':3},index=[0])

In [94]:
model.predict(dataNew)

array([0], dtype=int64)